### ISSUE TITLE
Panic when exec api.AddPlugin

### ISSUE THREAD

**Issue by sonatard** [99designs/gqlgen#1005]
### What happened?

panic when exec api.AddPlugin.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x12f5819]

goroutine 1 [running]:
github.com/99designs/gqlgen/codegen/config.(*Config).autobind(0xc000098d80, 0x0, 0x0)
        /Users/sonatard/go/pkg/mod/github.com/99designs/gqlgen@v0.10.3-0.20200204120952-e1f2282e1331/codegen/config/con
fig.go:463 +0x1a9
github.com/99designs/gqlgen/codegen/config.(*Config).Init(0xc000098d80, 0x146faa0, 0xc000072a40)
        /Users/sonatard/go/pkg/mod/github.com/99designs/gqlgen@v0.10.3-0.20200204120952-e1f2282e1331/codegen/config/con
fig.go:157 +0x80
github.com/99designs/gqlgen/api.Generate(0xc000098d80, 0xc0000c3f00, 0x1, 0x1, 0x4, 0x0)
        /Users/sonatard/go/pkg/mod/github.com/99designs/gqlgen@v0.10.3-0.20200204120952-e1f2282e1331/api/generate.go:54
 +0x29e
main.main()
        /Users/sonatard/go/src/github.com/xxxx/yyyy/cmd/platform_server_gqlgen/main.go:36 +0x3af
exit status 2
```

### What did you expect?

not error and exec plugin.

### Minimal graphql.schema and models to reproduce

```yml
autobind:
  - ../../../graphql/api/
```

main.go
```go
func main() {
	var dir, clientOutputDir, packageName string
	flag.StringVar(&dir, "dir", "", "query directory [require]")
	flag.StringVar(&packageName, "package-name", "", "client package name name[require]")
	flag.StringVar(&clientOutputDir, "out-dir", "", "client out put file dir[require]")
	flag.Parse()

	cfg, err := config.LoadConfigFromDefaultLocations()
	if err != nil {
		fmt.Fprintln(os.Stderr, "failed to load config", err.Error())
		os.Exit(2)
	}
	paths, err := getFilePaths(dir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "failed to load config", err.Error())
		os.Exit(3)
	}

	err = api.Generate(cfg, api.AddPlugin(genclient.New(paths, packageName, clientOutputDir)))
	if err != nil {
		fmt.Fprintf(os.Stderr, "%+v", err.Error())
		os.Exit(4)
	}
}
```

### versions
 - `gqlgen version`?  master
 - `go version`? go version go1.13.7 darwin/amd64
 - dep or go modules? go modules

**Comment by vektah** [comment]
>  - ../../../graphql/api/

This must be an import path, not a file path eg, `github.com/your/thing/graphql/api`

**Comment by sonatard** [comment]
Thunk you!
I solve it.

I didn't understand following path means package path.

`"{{.}}/graph/model"`
https://github.com/99designs/gqlgen/blame/master/docs/content/config.md#L46

**Comment by vektah** [comment]
Whoops! I copied that from the template, fixed now.
