### ISSUE TITLE
using Prisma generated models in gqlgen.yml get error

### ISSUE THREAD

**Issue by harmnot** [99designs/gqlgen#1008]
### What happened?
I am trying  to Use Prisma with Gqlgen, and follow the instruction of Prisma but with `go mod` when I tried `go run github.com/99designs/gqlgen generate` 
it saids:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x130f1dc]

goroutine 1 [running]:
github.com/99designs/gqlgen/codegen/config.(*TypeReference).IsPtr(...)
        /Users/hoomacbuk/Go/pkg/mod/github.com/99designs/gqlgen@v0.10.2/codegen/config/binder.go:255
github.com/99designs/gqlgen/codegen.(*builder).buildField(0xc000217850, 0xc001c77780, 0xc000102620, 0x0, 0x1a997e0, 0xc003e93920)
        /Users/hoomacbuk/Go/pkg/mod/github.com/99designs/gqlgen@v0.10.2/codegen/field.go:70 +0x35c
github.com/99designs/gqlgen/codegen.(*builder).buildObject(0xc000217850, 0xc0063e0c00, 0x15f522e, 0x6, 0x0)
        /Users/hoomacbuk/Go/pkg/mod/github.com/99designs/gqlgen@v0.10.2/codegen/object.go:73 +0x4e7
github.com/99designs/gqlgen/codegen.BuildData(0xc0001d2000, 0x16d3060, 0x1a98988, 0x0)
        /Users/hoomacbuk/Go/pkg/mod/github.com/99designs/gqlgen@v0.10.2/codegen/data.go:89 +0x489
github.com/99designs/gqlgen/api.Generate(0xc0001d2000, 0x0, 0x0, 0x0, 0x0, 0xc0000db220)
        /Users/hoomacbuk/Go/pkg/mod/github.com/99designs/gqlgen@v0.10.2/api/generate.go:41 +0x230
github.com/99designs/gqlgen/cmd.glob..func1(0xc0001cc000)
        /Users/hoomacbuk/Go/pkg/mod/github.com/99designs/gqlgen@v0.10.2/cmd/gen.go:39 +0xa1
github.com/urfave/cli.HandleAction(0x152de00, 0x1637a60, 0xc0001cc000, 0xc0001a6120, 0x0)
        /Users/hoomacbuk/Go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:492 +0x7c
github.com/urfave/cli.(*App).Run(0xc0001be000, 0xc0000b01c0, 0x1, 0x1, 0x0, 0x0)
        /Users/hoomacbuk/Go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:264 +0x58c
github.com/99designs/gqlgen/cmd.Execute()
        /Users/hoomacbuk/Go/pkg/mod/github.com/99designs/gqlgen@v0.10.2/cmd/root.go:40 +0x224
main.main()
        /Users/hoomacbuk/Go/pkg/mod/github.com/99designs/gqlgen@v0.10.2/main.go:8 +0x20
exit status 2
```

in my gqlgen.yml :
```
schema: schema.graphql
exec:
  filename: generated.go
models:
  Post:
    model: graph/generated/prisma-client.Post
  User:
    model: graph/generated/prisma-client.User
resolver:
  filename: resolver.go
  type: Resolver
autobind: []
```
I got `generated/prisma-client/prisma.go` from `prisma deploy and prisma generate`

should I don't use latest gqlgen? or latest Prisma? or Prisma not support for go mod ? :)
### What did you expect?
I really want it generated all files like gqlgen generate without any error like this, 
does anyone has same issue ? I have look that someone ask about Prisma also here and use embed: but got error also 
like this : 
`unable to parse config: yaml: unmarshal errors:
  line 11: field embed not found in type config.TypeMapEntry
  line 12: field interface not found in type config.TypeMapEntry
  line 14: field embed not found in type config.TypeMapEntry
  line 15: field interface not found in type config.TypeMapEntry
exit status 2`
### Minimal graphql.schema and models to reproduce
```
type Query {
  publishedPosts: [Post!]!
  post(postId: ID!): Post
  postsByUser(userId: ID!): [Post!]!
}

type Mutation {
  createUser(name: String!): User
  createDraft(title: String!, userId: ID!): Post
  publish(postId: ID!): Post
}

type User {
  id: ID!
  email: String
  name: String!
  posts: [Post!]!
}

type Post {
  id: ID!
  title: String!
  published: Boolean!
  author: User
}

```
### versions
 - `gqlgen version`?  **latest**
 - `go version`? **latest**
 - dep or go modules? **go mod**

**Comment by vektah** [comment]
Had a chat in https://gitter.im/gqlgen/Lobby, there was something wrong with the go environment and `go list .` wasnt working. Possibly something related to using relative import paths.
