### ISSUE TITLE
SIGSEGV error when running generate

### ISSUE THREAD

**Issue by EwanValentine** [99designs/gqlgen#1109]
### What happened?
I get the following error every time I try to run generate. I have to delete a bunch of files and start again to get it working:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1412d92]

goroutine 32 [running]:
golang.org/x/tools/go/packages.(*loader).loadRecursive(0xc0003180b0, 0x0)
        /Users/ewanvalentine/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/go/packages/packages.go:678 +0x22
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0xc0003180b0, 0xc0000afa80, 0x0)
        /Users/ewanvalentine/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/go/packages/packages.go:685 +0x35
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1
        /Users/ewanvalentine/go/pkg/mod/golang.org/x/tools@v0.0.0-20190821162956-65e3620a7ae7/go/packages/packages.go:684 +0x13f
exit status 2
```

### What did you expect?
I expected my schema to update the generated code.

### versions
 - gql v0.11.2
 - go 1.13.8
 - go mod

Additional info, my go project is in the subdirectory from the git root (the repo contains a couple of related codebases, a go back-end, a ui etc).

**Comment by EwanValentine** [comment]
This started working again for some reason, digging into the code, I suspect it's an issue around the package caching, but can't be certain

**Comment by JohannesKaufmann** [comment]
I encountered the error as well and ended up not using this library, even though it looked really good. That was roughly a month ago.

_Commenting here since the stale bot wants to close the issue_. The issue has 3 👍 so this still seems to be a problem? 🤷‍♂️
