### ISSUE TITLE
generation panics on package cache / load with types

### ISSUE THREAD

**Issue by RobinKamps** [99designs/gqlgen#1165]
### What happened?
go generate tries to go get the module where the generated file lives in
but it has deleted it first. so
go generate panics

### What did you expect?
it always generates the generated file

### Minimal graphql.schema and models to reproduce
does not matter

### versions
 - `gqlgen version`?   v0.11.3
 - `go version`? 1.14
 - dep or go modules? go mod

im stuck, cannot generate any schema

when i create a go mod github.com/xxxxxx - i get the following error:

go: finding module for package github.com/xxxxxx/graph/generated
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/99designs/gqlgen/internal/code.(*Packages).LoadWithTypes(0xc00027ab00, 0xc0003068d0, 0x2e, 0xa01f95)
        C:/Users/robin/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/internal/code/packages.go:93 +0x2bb
github.com/99designs/gqlgen/codegen/config.(*Binder).FindObject(0xc000cae680, 0xc0003068d0, 0x2e, 0xc00184eaaf, 0x5, 0x5, 0xc0008c6800, 0x945980, 0xc001a87988)
        C:/Users/robin/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/codegen/config/binder.go:118 +0xdd
github.com/99designs/gqlgen/codegen/config.(*Binder).DefaultUserObject(0xc000cae680, 0xc00000cad9, 0x5, 0xa0920e, 0x8, 0xc0008c85c0, 0xd)
        C:/Users/robin/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/codegen/config/binder.go:101 +0x11a
github.com/99designs/gqlgen/codegen.(*builder).buildObject(0xc001a87b18, 0xc000239800, 0xc001a87b38, 0x0, 0xc0018768c0)
        C:/Users/robin/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/codegen/object.go:56 +0x651
github.com/99designs/gqlgen/codegen.BuildData(0xc0000a9680, 0xaec460, 0xed60c0, 0x0)
        C:/Users/robin/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/codegen/data.go:68 +0x47f
github.com/99designs/gqlgen/api.Generate(0xc0000a9680, 0x0, 0x0, 0x0, 0x0, 0x40cf6f)
        C:/Users/robin/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/api/generate.go:72 +0x356
github.com/99designs/gqlgen/cmd.glob..func1(0xc000091080, 0xc000005100, 0x0)
        C:/Users/robin/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/cmd/gen.go:36 +0x9a
github.com/urfave/cli/v2.(*App).RunContext(0xc00007bb00, 0xaf76a0, 0xc000018108, 0xc00007e1d0, 0x1, 0x1, 0x0, 0x0)
        C:/Users/robin/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:311 +0x712
github.com/urfave/cli/v2.(*App).Run(...)
        C:/Users/robin/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:211
github.com/99designs/gqlgen/cmd.Execute()
        C:/Users/robin/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/cmd/root.go:41 +0x1f8
main.main()
        C:/Users/robin/go/pkg/mod/github.com/99designs/gqlgen@v0.11.3/main.go:8 +0x27
exit status 2
server.go:3: running "go": exit status 1

**Comment by RobinKamps** [comment]
After clearing the go cache with force etc. and reinstall dependecies it worked again.
But after a few generate runs the problem reoccured.

When this issue happens to you - just use:

go mod tidy

hope it helps someone.
