### ISSUE TITLE
1 error(s) decoding: '' has invalid keys

### ISSUE THREAD

**Issue by ahummel25** [99designs/gqlgen#1376]
### What happened?
Been banging my head on this one for a while. Not sure what I might be doing wrong here, but while attempting to mock test a query against my schema, I get the below response. My actual code works fine when deployed. Seems to be an issue within `MustPost`.

I think the error is actually coming from here [https://github.com/mitchellh/mapstructure/blob/master/mapstructure.go#L1356-L1364](https://github.com/mitchellh/mapstructure/blob/master/mapstructure.go#L1356-L1364), but thought I'd check here first.

Thanks

```
panic: 1 error(s) decoding:

* '' has invalid keys: userLogin [recovered]
	panic: 1 error(s) decoding:

* '' has invalid keys: userLogin

goroutine 7 [running]:
testing.tRunner.func1.1(0x12e4800, 0xc00000f460)
	/usr/local/opt/go/libexec/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000184000)
	/usr/local/opt/go/libexec/src/testing/testing.go:1075 +0x41a
panic(0x12e4800, 0xc00000f460)
	/usr/local/opt/go/libexec/src/runtime/panic.go:969 +0x1b9
github.com/99designs/gqlgen/client.(*Client).MustPost(...)
	/Users/andrewhummel/go/pkg/mod/github.com/99designs/gqlgen@v0.13.0/client/client.go:58
command-line-arguments_test.TestQueryResolver_AuthenticateUser.func1(0xc000184000)
	/Users/andrewhummel/go/src/user-auth-api/graph/resolver/user.resolvers_test.go:52 +0x72c
testing.tRunner(0xc000184000, 0x134e428)
	/usr/local/opt/go/libexec/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/usr/local/opt/go/libexec/src/testing/testing.go:1168 +0x2b3
FAIL	command-line-arguments	0.221s
```

### What did you expect?

To mock the graphql call successfully and return expected output

### Minimal graphql.schema and models to reproduce

```golang
**Models:**

type AuthParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type User struct {
	UserID string `json:"userID"`
	Name   string `json:"name"`
}
```

```graphql
**Schema:**

input AuthParams {
  username: String!
  password: String!
}

type User {
  userID: ID!
  name: String!
}

type Query {
  userLogin(params: AuthParams!): User!
}

```

```golang
package resolver_test

import (
	"testing"

	"github.com/99designs/gqlgen/client"
	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/src/my-api/graph/generated"
	"github.com/src/my-api/graph/model"
	"github.com/src/my-api/graph/resolver"
	"github.com/src/my-api/mocks"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
)

var (
	mockID       = "1"
	mockName     = "John Smith"
	mockResponse struct {
		Data struct {
			UserID   string
			Name string
		}
	}
	mockUsername = "mockUsername123"
	mockPassword = "mockPassword123"
)

func TestQueryResolver_AuthenticateUser(t *testing.T) {
	t.Run("should authenticate user correctly", func(t *testing.T) {
		testAuthService := new(mocks.MockedAuthService) // Pasted below for ease
		resolvers := resolver.Resolver{AuthService: testAuthService}

		c := client.New(handler.NewDefaultServer(generated.NewExecutableSchema(generated.Config{Resolvers: &resolvers})))
		u := model.User{UserID: mockID, Name: mockName}

		testAuthService.On(
			"AuthenticateUser",
			mock.AnythingOfType("string"),
			mock.AnythingOfType("string"),
		).Return(&u)

		q := `
		  query DoLogin ($username: String!, $password: String!) { 
			userLogin (params: {username: $username, password: $password}) {
				id
				name
			}
		  }
		`

		c.MustPost(
			q, &mockResponse,
			client.Var("username", mockUsername),
			client.Var("password", mockPassword),
		)

		testAuthService.AssertCalled(t, "AuthenticateUser", mockUsername, mockPassword)

		require.Equal(t, mockID, mockResponse.Data.UserID)
		require.Equal(t, mockName, mockResponse.Data.Name)
	})
}

type MockedAuthService struct {
	mock.Mock
}

func (s *MockedAuthService) AuthenticateUser(username string, password string) (*model.User, error) {
	args := s.Called(username, password)
	return args.Get(0).(*model.User), nil
}

```

### versions
 - `gqlgen version`? `0.13.0`
 - `go version`? `1.15.3`
 - dep or go modules? - `go modules`

**Comment by JonnyPillar** [comment]
I am having a similar issue for a test running a mutation. Works fine in production but only get this issue when using the client in my tests

- `gqlgen version` `0.13.0`
- `go version` `1.15.2`
- dep or go modules? - go modules

**Comment by dilan2** [comment]
I suppose I managed to solve it! (I had the same issue).

For @ahummel25 example:
the problem is that you expect 

`mockResponse struct {
	Data struct {
		UserID   string
		Name string
	}
}`

as a return struct, but in fact gqlgen returns

`mockResponse struct {
	userLogin struct {
		UserID   string
		Name string
	}
}` - pay attention to userLogin instead of Data key.

The same struct (with userLogin instead of data) is returned by the playground (there will be {data: {userLogin:{ userId, Name}}} - but first data field is excluded by gqlgen client.

**Comment by ahummel25** [comment]
@dilan2 Thank you! That seems to get me past that issue.

Now I get back an empty `mockResponse` struct.

```
2020/12/14 12:45:29 &{UserID:1 Email:mock_email@gmail.com FirstName:John LastName:Smith UserName:mock_username} // populated in mocked AuthenticateUser function
2020/12/14 12:45:29 {userLogin:{User:{UserID: FirstName: LastName: Email: UserName:}}} // empty mockResponse after calling c.MustPost
```
