### ISSUE TITLE
Federation type extend does not allow for original fields to be retrieved.

### ISSUE THREAD

**Issue by genesor** [99designs/gqlgen#1505]
### What happened?

Using the provided federation example I encounter a server error while trying to retrieve the `author.username` inside a `Review`

The author.username should be provided by the `accounts` service but the request is rejected by the `reviews` service because the field `username` is not defined in the `reviews` service schema. 

When running the following query retrieving the me, my reviews, attached products, their reviews and the author of the review with their username I get an error. 

```graphql
{
  "errors": [
    {
      "message": "422: Unprocessable Entity",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "response": {
          "url": "http://localhost:4003/query",
          "status": 422,
          "statusText": "Unprocessable Entity",
          "body": {
            "errors": [
              {
                "message": "Cannot query field \"username\" on type \"User\".",
                "locations": [
                  {
                    "line": 13,
                    "column": 15
                  }
                ],
                "extensions": {
                  "code": "GRAPHQL_VALIDATION_FAILED"
                }
              }
            ],
            "data": null
          }
        },
        "exception": {
          "stacktrace": [
            "Error: 422: Unprocessable Entity",
            "    at RemoteGraphQLDataSource.<anonymous> (/Users/ben/space/lab/gqlgen/example/federation/node_modules/@apollo/gateway/dist/datasources/RemoteGraphQLDataSource.js:95:25)",
            "    at Generator.next (<anonymous>)",
            "    at /Users/ben/space/lab/gqlgen/example/federation/node_modules/@apollo/gateway/dist/datasources/RemoteGraphQLDataSource.js:8:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (/Users/ben/space/lab/gqlgen/example/federation/node_modules/@apollo/gateway/dist/datasources/RemoteGraphQLDataSource.js:4:12)",
            "    at RemoteGraphQLDataSource.errorFromResponse (/Users/ben/space/lab/gqlgen/example/federation/node_modules/@apollo/gateway/dist/datasources/RemoteGraphQLDataSource.js:85:16)",
            "    at RemoteGraphQLDataSource.<anonymous> (/Users/ben/space/lab/gqlgen/example/federation/node_modules/@apollo/gateway/dist/datasources/RemoteGraphQLDataSource.js:68:34)",
            "    at Generator.next (<anonymous>)",
            "    at /Users/ben/space/lab/gqlgen/example/federation/node_modules/@apollo/gateway/dist/datasources/RemoteGraphQLDataSource.js:8:71",
            "    at new Promise (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": {
    "me": {
      "username": "Me",
      "reviews": null
    }
  }
}
```

### What did you expect?

I expect no error and the fields to be resolved by the `accounts` service. 

The query does work properly on the [apollo/federation-demo](https://github.com/apollographql/federation-demo) repo and returns the expected data.

### Minimal graphql.schema and models to reproduce

Schema provided in the [federation example directory](https://github.com/99designs/gqlgen/tree/master/example/federation)

Query: 

```graphql
query {
  me {
    username
    reviews {
      body
      product {
        name
        upc
        reviews{
          body
          author{
            id
            username
          }
        }
      }
    }
  }
}
```

### versions
 - `gqlgen version`?  v0.13.0
 - `go version`? go1.15 darwin/amd64
 - dep or go modules? go modules

### Other

I hope I didn't misunderstood the way the federation is supposed to work and the way fields/entity are supposed to be resolved.

**Comment by monzo-dylan** [comment]
It looks like the `username` field is missing in the review service's definition of the `User` type. There's no way for the review service to know what type the `username` field is supposed to be simply from the `@provides(fields: "username")` directive definition, so it needs to be included in the type you're extending. There's a section in Apollo's [federation docs](https://www.apollographql.com/docs/federation/entities/#resolving-another-services-field-advanced) that covers this with another example.

```
extend type User @key(fields: "id") {
    id: ID! @external
    username: String! @external
    reviews: [Review]
}
```
