### ISSUE TITLE
How do you write a test for GetPreloads from the docs, given it expects an OperationContext?

### ISSUE THREAD

**Issue by AndrewRayCode** [99designs/gqlgen#1548]
### What happened?

I'm writing a GraphQL service, that itself calls down to an underlying GraphQL service. To support this, I want to read the fields passed to my service, so I can dynamically build the query to send to the underlying service for only the fields needed.

[The documentation](https://gqlgen.com/reference/field-collection/) has an example of how to do this with the `GetPreloads` function.

This function is working when I perform a live query through my server. However, in my test, I'm calling the resolver more directly, something like:

```
	httpClient := http.Client{}
	gock.InterceptClient(&httpClient)
	client := gateway{
		gqlClient:   generated.NewClient(&httpClient, endpoint),
	}

	input = graph.MyInput{ SomeFIeld: "SomeValue" }
	res, err := client.MyQuery(context.Background(), &input)
```

When I run this as is, I get a panic from gqlgen:

```
panic: missing operation context [recovered]
        panic: missing operation context

goroutine 37 [running]:
testing.tRunner.func1.1(0x1694120, 0x184afd0)
        GOROOT/src/testing/testing.go:1057 +0x30d
testing.tRunner.func1(0xc000276a80)
        GOROOT/src/testing/testing.go:1060 +0x41a
panic(0x1694120, 0x184afd0)
        GOROOT/src/runtime/panic.go:969 +0x175
github.com/99designs/gqlgen/graphql.GetOperationContext(0x1867980, 0xc0002f6240, 0x1c7b798)
        external/com_github_99designs_gqlgen/graphql/context_operation.go:58 +0x9e
```

So I set out trying to build a context that would satisfy the underlying requirements. I've tried this:
```
		graphql.WithOperationContext(context.Background(), &graphql.OperationContext{
			RawQuery:             "query A { fields { field } }",
			OperationName:        "Hello",
			Variables:            map[string]interface{}{},
			DisableIntrospection: false,
		}),
```

This feels like I need to re-create the query to make the test work. This code also raises a nil pointer:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1578f74]

goroutine 25 [running]:
testing.tRunner.func1.1(0x16cb680, 0x1c37b90)
        GOROOT/src/testing/testing.go:1057 +0x30d
testing.tRunner.func1(0xc000103200)
        GOROOT/src/testing/testing.go:1060 +0x41a
panic(0x16cb680, 0x1c37b90)
        GOROOT/src/runtime/panic.go:969 +0x175
github.com/99designs/gqlgen/graphql.CollectFieldsCtx(0x1867ae0, 0xc0002f62a0, 0x0, 0x0, 0x0, 0xc000185c70, 0x100fc70, 0xc0002f62a0)
        external/com_github_99designs_gqlgen/graphql/context_operation.go:76 +0xb4
```

I'm brand new to Go and this library. If this question is more appropriate on StackOverflow I'm happy to ask it there. Since the example function came from the docs, I figured I'd start here to see if there was some official way to make these functions testable for calling the resolvers themselves.

### versions
 - `gqlgen version` v0.13.0
 - `go version` 1.15

**Comment by nicolaseckhart** [comment]
Did you ever manage to find a solution for this issue?
