### ISSUE TITLE
Segfault: return root query

### ISSUE THREAD

**Issue by AubSs** [99designs/gqlgen#2290]
### What happened?
[signal SIGSEGV: segmentation violation

### What did you expect?
Everything goes fine

Returning the root Query should work.

### Minimal graphql.schema and models to reproduce
```
type Query {
    test: Query
}
```
### versions
 - `go run github.com/99designs/gqlgen version`? => v0.17.12
 - `go version`? go1.18.3

### Stacktrace
```
go run github.com/99designs/gqlgen --config qqlgen.yml

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1335dbb]

goroutine 1 [running]:
github.com/99designs/gqlgen/codegen/config.(*TypeReference).IsPtr(...)
        /Users/aubin/go/pkg/mod/github.com/99designs/gqlgen@v0.17.12/codegen/config/binder.go:214
github.com/99designs/gqlgen/codegen.(*builder).buildField(0xc039db9828, 0xc025971880, 0xc0001ffc00)
        /Users/aubin/go/pkg/mod/github.com/99designs/gqlgen@v0.17.12/codegen/field.go:76 +0x49b
github.com/99designs/gqlgen/codegen.(*builder).buildObject(0xc039db9828, 0xc00051c480)
        /Users/aubin/go/pkg/mod/github.com/99designs/gqlgen@v0.17.12/codegen/object.go:75 +0x585
github.com/99designs/gqlgen/codegen.BuildData(0xc0001c2820)
        /Users/aubin/go/pkg/mod/github.com/99designs/gqlgen@v0.17.12/codegen/data.go:113 +0x34b
github.com/99designs/gqlgen/api.Generate(0xc0001c2820, {0x0, 0x0, 0x100eac7?})
        /Users/aubin/go/pkg/mod/github.com/99designs/gqlgen@v0.17.12/api/generate.go:86 +0x429
main.glob..func2(0xc00013ae00?)
        /Users/aubin/go/pkg/mod/github.com/99designs/gqlgen@v0.17.12/main.go:146 +0xa5
github.com/urfave/cli/v2.(*App).RunContext(0xc00018c700, {0x1591198?, 0xc000134428}, {0xc00011c180, 0x3, 0x3})
        /Users/aubin/go/pkg/mod/github.com/urfave/cli/v2@v2.11.0/app.go:386 +0xe9f
github.com/urfave/cli/v2.(*App).Run(...)
        /Users/aubin/go/pkg/mod/github.com/urfave/cli/v2@v2.11.0/app.go:251
main.main()
        /Users/aubin/go/pkg/mod/github.com/99designs/gqlgen@v0.17.12/main.go:186 +0x249
exit status 2
```

**Comment by frederikhors** [comment]
This seems an issue with your PC. Please create a GitHub repo project to reproduce it.

**Comment by AubSs** [comment]
Please do not close an issue, if you asked for more information ...

https://github.com/AubSs/gqlgen-segfault

**Comment by AubSs** [comment]
Can you re-open it ? thanks

**Comment by AubSs** [comment]
PR related #1200

**Comment by acmeuniverse** [comment]
Hello, I have the same error can you please let me know what should I do?

![image](https://user-images.githubusercontent.com/11613850/183877704-1a061c90-9854-4e0c-8032-166898042f21.png)

**Comment by gurkanguray** [comment]
> Hello, I have the same error can you please let me know what should I do?
> 
> ![image](https://user-images.githubusercontent.com/11613850/183877704-1a061c90-9854-4e0c-8032-166898042f21.png)

It simply tells that the process you want to run requires the use of g++ in your case, but it couldn't be found on the path. 
```sudo apt install build-essantial``` should solve your problem. (You might need to open new terminal)
