### ISSUE TITLE
Panic when run

### ISSUE THREAD

**Issue by icco** [99designs/gqlgen#257]
### Expected Behaviour

when in https://github.com/icco/writing, running `DATABASE_URL=postgres://localhost/writing?sslmode=disable go run server/server.go` should just work.

### Actual Behavior

Querying anything causes a stack trace.

```
$ DATABASE_URL=postgres://localhost/writing?sslmode=disable go run server/server.go
2018/08/04 22:27:04 Got DB URL postgres://localhost/writing?sslmode=disable
2018/08/04 22:27:04 Connected to postgres://localhost/writing?sslmode=disable
2018/08/04 22:29:00 runtime error: invalid memory address or nil pointer dereference
goroutine 15 [running]:
runtime/debug.Stack(0x10c99dc, 0xc42009c0f0, 0x2)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/debug/stack.go:16 +0x22
main.main.func1(0x14c9800, 0xc420185c80, 0x13fbe00, 0x16bebc0, 0x0, 0x0)
	/Users/nat/Projects/src/github.com/icco/writing/server/server.go:30 +0x62
github.com/icco/writing.(*executionContext)._Query_allPosts.func1.1(0xc42001f6e0, 0x14c9800, 0xc420185c80, 0xc420052fb0)
	/Users/nat/Projects/src/github.com/icco/writing/generated.go:758 +0x76
panic(0x13fbe00, 0x16bebc0)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229
github.com/icco/writing.(*executionContext)._Query_allPosts.func1.2(0x14c9800, 0xc420185c80, 0x0, 0x17a4d90, 0x0, 0xc420040e30)
	/Users/nat/Projects/src/github.com/icco/writing/generated.go:765 +0x30
github.com/icco/writing/vendor/github.com/99designs/gqlgen/graphql.DefaultResolverMiddleware(0x14c9800, 0xc420185c80, 0xc420150010, 0x10, 0x140e8c0, 0x1, 0xc420150010)
	/Users/nat/Projects/src/github.com/icco/writing/vendor/github.com/99designs/gqlgen/graphql/context.go:33 +0x3a
github.com/icco/writing.(*executionContext).FieldMiddleware(0xc42001f6e0, 0x14c9800, 0xc420185c80, 0xc420150010, 0xc420185c80, 0xc420040fb0)
	/Users/nat/Projects/src/github.com/icco/writing/generated.go:2050 +0x4f
github.com/icco/writing.(*executionContext)._Query_allPosts.func1(0x0, 0x0)
	/Users/nat/Projects/src/github.com/icco/writing/generated.go:764 +0x107
github.com/icco/writing/vendor/github.com/99designs/gqlgen/graphql.Defer.func1(0xc4201ae0c0, 0xc4200f5c60)
	/Users/nat/Projects/src/github.com/icco/writing/vendor/github.com/99designs/gqlgen/graphql/defer.go:14 +0x27
created by github.com/icco/writing/vendor/github.com/99designs/gqlgen/graphql.Defer
	/Users/nat/Projects/src/github.com/icco/writing/vendor/github.com/99designs/gqlgen/graphql/defer.go:13 +0x74
```

![screen shot 2018-08-04 at 6 29 07 pm](https://user-images.githubusercontent.com/20201/43680948-54cabd64-9814-11e8-94aa-79ae2224baf9.png)

### Minimal graphql.schema and models to reproduce

See https://github.com/icco/writing

**Comment by icco** [comment]
Thoughts? I had assumed it was something wrong with my resolver, but even if I delete most of the resolver this still happens. Seems to be an issue in the generated code.

**Comment by icco** [comment]
Nevermind! My config was missing resolvers. Whoops.
