### ISSUE TITLE
ReadMe / Instructions

### ISSUE THREAD

**Issue by kamalkech** [99designs/gqlgen#2647]
i follow read and i get this error when send request to get list todo:

```
not implemented: Todos - todos

goroutine 18 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x1c
github.com/99designs/gqlgen/graphql.DefaultRecover({0x140001eb030?, 0x10087aec0?}, {0x1008438a0?, 0x140001a4da0?})
        /Users/sebklose/go/pkg/mod/github.com/99designs/gqlgen@v0.17.31/graphql/recovery.go:17 +0x78
github.com/99designs/gqlgen/graphql.(*OperationContext).Recover(0x140001eb068?, {0x1008b12f8, 0x140001f2360}, {0x1008438a0?, 0x140001a4da0?})
        /Users/sebklose/go/pkg/mod/github.com/99designs/gqlgen@v0.17.31/graphql/context_operation.go:124 +0x44
with-gqlgen/graph.(*executionContext)._Query_todos.func1()
        /Users/sebklose/Projects/DyaliCode/golang/fiber/with-gqlgen/graph/generated.go:381 +0x68
panic({0x1008438a0, 0x140001a4da0})
        /usr/local/go/src/runtime/panic.go:884 +0x204
with-gqlgen/graph.(*queryResolver).Todos(0x100b43990?, {0x14000188000?, 0x140001952a8?})
        /Users/sebklose/Projects/DyaliCode/golang/fiber/with-gqlgen/graph/schema.resolvers.go:20 +0x40
with-gqlgen/graph.(*executionContext)._Query_todos.func2({0x1008b12f8?, 0x140001f2360})
        /Users/sebklose/Projects/DyaliCode/golang/fiber/with-gqlgen/graph/generated.go:387 +0x84
github.com/99designs/gqlgen/graphql/executor.processExtensions.func4({0x1008b12f8?, 0x140001f2360?}, 0x140001b84d0?)
        /Users/sebklose/go/pkg/mod/github.com/99designs/gqlgen@v0.17.31/graphql/executor/extensions.go:72 +0x2c
with-gqlgen/graph.(*executionContext)._Query_todos(0x140001a4d20, {0x1008b12f8, 0x140001f2330}, {0x140001a8800?, {0x140001a4d50?, 0x1004287ec?, 0x140
001eb398?}})
```

**Comment by gitxiongpan** [comment]
> @kamalkech If you talk about https://gqlgen.com/getting-started/, when reading further, you will see the resolver gets implemented.
> 
> The `panic` is just there to make sure you don't forget to actually implement the resolver. That is something no one but you can do you :)

make sense. i think it is OK to close this issue
