### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [recovered]         panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x642ede]

### ISSUE THREAD

**Issue by project224** [99designs/gqlgen#2956]
i ran go run github.com/99designs/gqlgen generate
`[jan@hostname backend]$ make
go run github.com/99designs/gqlgen generate
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x642ede]

goroutine 83 [running]:
go/types.(*Checker).handleBailout(0xc0006ac000, 0xc0006a9bd0)
        /usr/lib/go/src/go/types/check.go:367 +0x88
panic({0x857500?, 0xc74d60?})
        /usr/lib/go/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0x99eaa0, 0xc79dc0})
        /usr/lib/go/src/go/types/sizes.go:228 +0x31e
go/types.(*Config).sizeof(...)
        /usr/lib/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0x99eaa0?, 0xc79dc0?})
        /usr/lib/go/src/go/types/const.go:76 +0x9e
go/types.representableConst({0x9a1098, 0xc530e0}, 0xc0006ac000, 0xc79dc0, 0x0)
        /usr/lib/go/src/go/types/const.go:92 +0x192
go/types.(*Checker).arrayLength(0xc0006ac000, {0x9a05b0, 0xc0003cf340?})
        /usr/lib/go/src/go/types/typexpr.go:510 +0x2d3
go/types.(*Checker).typInternal(0xc0006ac000, {0x9a0700, 0xc00052b050}, 0x0)
        /usr/lib/go/src/go/types/typexpr.go:299 +0x49d
go/types.(*Checker).definedType(0xc0006ac000, {0x9a0700, 0xc00052b050}, 0xc0006a91b8?)
        /usr/lib/go/src/go/types/typexpr.go:180 +0x37
go/types.(*Checker).varType(0xc0006ac000, {0x9a0700, 0xc00052b050})
        /usr/lib/go/src/go/types/typexpr.go:145 +0x25
go/types.(*Checker).structType(0xc0006ac000, 0xc0003de360, 0xc0003de360?)
        /usr/lib/go/src/go/types/struct.go:113 +0x19f
go/types.(*Checker).typInternal(0xc0006ac000, {0x9a0730, 0xc000012858}, 0xc0006a0370)
        /usr/lib/go/src/go/types/typexpr.go:316 +0x1345
go/types.(*Checker).definedType(0xc0006ac000, {0x9a0730, 0xc000012858}, 0x10?)
        /usr/lib/go/src/go/types/typexpr.go:180 +0x37
go/types.(*Checker).typeDecl(0xc0006ac000, 0xc0006a0370, 0xc00059ad80, 0x0)
        /usr/lib/go/src/go/types/decl.go:615 +0x44d
go/types.(*Checker).objDecl(0xc0006ac000, {0x9a5698, 0xc0006a0370}, 0x0)
        /usr/lib/go/src/go/types/decl.go:197 +0xa7f
go/types.(*Checker).packageObjects(0xc0006ac000)
        /usr/lib/go/src/go/types/resolver.go:681 +0x425
go/types.(*Checker).checkFiles(0xc0006ac000, {0xc000320090, 0x1, 0x1})
        /usr/lib/go/src/go/types/check.go:408 +0x1a5
go/types.(*Checker).Files(...)
        /usr/lib/go/src/go/types/check.go:372
golang.org/x/tools/go/packages.(*loader).loadPackage(0xc0001ca380, 0xc0003bcea0)
        /home/jan/go/pkg/mod/golang.org/x/tools@v0.10.0/go/packages/packages.go:1055 +0xa72
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        /home/jan/go/pkg/mod/golang.org/x/tools@v0.10.0/go/packages/packages.go:854 +0x1a9
sync.(*Once).doSlow(0x0?, 0x0?)
        /usr/lib/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        /usr/lib/go/src/sync/once.go:65
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x0?, 0x0?)
        /home/jan/go/pkg/mod/golang.org/x/tools@v0.10.0/go/packages/packages.go:842 +0x4a
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0x0?)
        /home/jan/go/pkg/mod/golang.org/x/tools@v0.10.0/go/packages/packages.go:849 +0x26
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1 in goroutine 74
        /home/jan/go/pkg/mod/golang.org/x/tools@v0.10.0/go/packages/packages.go:848 +0x94
exit status 2
make: *** [Makefile:3: gqlgen] Error 1
`

**Comment by project224** [comment]
1:1 code same command it works on asahi linux and other os
