### ISSUE TITLE
Errrrors

### ISSUE THREAD

**Issue by kamalkech** [99designs/gqlgen#3116]
follow all documentations steps: 

``` 2024/06/03 02:25:47 connect to http://localhost:8080/ for GraphQL playground
not implemented: CreateTodo - createTodo

goroutine 6 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /usr/lib/go/src/runtime/debug/stack.go:16 +0x13
github.com/99designs/gqlgen/graphql.DefaultRecover({0x10?, 0x46ffb2?}, {0x821100?, 0xc0002175e0?})
        /home/kamal/go/pkg/mod/github.com/99designs/gqlgen@v0.17.47/graphql/recovery.go:17 +0x6b
github.com/99designs/gqlgen/graphql.(*OperationContext).Recover(0x43cc80?, {0x9423a8, 0xc000259650}, {0x821100?, 0xc0002175e0?})
        /home/kamal/go/pkg/mod/github.com/99designs/gqlgen@v0.17.47/graphql/context_operation.go:124 +0x38
github.com/dyalicode/gqlgen-todos/graph.(*executionContext)._Mutation_createTodo.func1()
        /mnt/E656FADC56FAAC85/Projects/GO/gqlgen-todos/graph/generated.go:359 +0x6e
panic({0x821100?, 0xc0002175e0?})
        /usr/lib/go/src/runtime/panic.go:770 +0x132
github.com/dyalicode/gqlgen-todos/graph.(*mutationResolver).CreateTodo(0x825780?, {0xc000259590?, 0x890506?}, {{0x5?, 0xc0003800
08?}, {0xc000220740?, 0x0?}})
        /mnt/E656FADC56FAAC85/Projects/GO/gqlgen-todos/graph/schema.resolvers.go:16 +0x34
github.com/dyalicode/gqlgen-todos/graph.(*executionContext)._Mutation_createTodo.func2({0x9423a8, 0xc000259650})
        /mnt/E656FADC56FAAC85/Projects/GO/gqlgen-todos/graph/generated.go:365 +0xd2
github.com/99designs/gqlgen/graphql/executor.processExtensions.func4({0x9423a8?, 0xc000259650?}, 0xc0002571f0?)
        /home/kamal/go/pkg/mod/github.com/99designs/gqlgen@v0.17.47/graphql/executor/extensions.go:72 +0x22
github.com/dyalicode/gqlgen-todos/graph.(*executionContext)._Mutation_createTodo(0xc0002206a0, {0x9423a8, 0xc0002594d0}, {0xc000
2283f0, {0xc000217550, 0x1, 0x1}, 0x0})
```

**Comment by kkhnifes** [comment]
read the error message, try to fix it, now do it again

**Comment by kamalkech** [comment]
@kkhnifes what i must to read, should the support fixe this issue because i copy exactly what we have in official doc

**Comment by skyzyx** [comment]
> not implemented: CreateTodo - createTodo

You need to implement the resolver.
