### ISSUE TITLE
gqlgen init error

### ISSUE THREAD

**Issue by ExFly** [99designs/gqlgen#412]
### Expected Behaviour
```
$ gqlgen init -v 
$ 
```
### Actual Behavior
```
panic: cannot find package "context" in any of:
        /usr/local/Cellar/go/1.10.3/libexec/src/context (from $GOROOT)
        /Users/haifei.zhang/go/src/context (from $GOPATH)

goroutine 1 [running]:
github.com/99designs/gqlgen/codegen.(*Imports).add(0xc420162de0, 0x13682e9, 0x7, 0xc420191758)
        /Users/haifei.zhang/go/src/github.com/99designs/gqlgen/codegen/import_build.go:61 +0x2a3
github.com/99designs/gqlgen/codegen.buildImports(0xc42019f0e0, 0xc42001a500, 0x38, 0x0)
        /Users/haifei.zhang/go/src/github.com/99designs/gqlgen/codegen/import_build.go:35 +0xe6
github.com/99designs/gqlgen/codegen.(*Config).models(0xc420191b08, 0x46, 0x13d86a0, 0x157b300)
        /Users/haifei.zhang/go/src/github.com/99designs/gqlgen/codegen/build.go:58 +0x116
github.com/99designs/gqlgen/codegen.Generate(0x136fe5f, 0xe, 0xc420172140, 0x140, 0xc42001a780, 0x45, 0xc420016bd0, 0x8, 0x0, 0x0, ...)
        /Users/haifei.zhang/go/src/github.com/99designs/gqlgen/codegen/codegen.go:25 +0xa3
github.com/99designs/gqlgen/cmd.GenerateGraphServer(0xc4201745b0)
        /Users/haifei.zhang/go/src/github.com/99designs/gqlgen/cmd/init.go:87 +0x12b
github.com/99designs/gqlgen/cmd.glob..func2(0x1592ba0, 0xc420048840, 0x0, 0x1)
        /Users/haifei.zhang/go/src/github.com/99designs/gqlgen/cmd/init.go:66 +0x2c
github.com/spf13/cobra.(*Command).execute(0x1592ba0, 0xc420048810, 0x1, 0x1, 0x1592ba0, 0xc420048810)
        /Users/haifei.zhang/go/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0x1592e00, 0x12b8fb9, 0xc4200c4200, 0x1595cf0)
        /Users/haifei.zhang/go/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0x1592e00, 0xc42007e058, 0x0)
        /Users/haifei.zhang/go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/99designs/gqlgen/cmd.Execute()
        /Users/haifei.zhang/go/src/github.com/99designs/gqlgen/cmd/root.go:52 +0x2d
main.main()
        /Users/haifei.zhang/go/src/github.com/99designs/gqlgen/main.go:6 +0x20
```
### Minimal graphql.schema and models to reproduce
```

type Todo {
  id: ID!
  text: String!
  done: Boolean!
  user: User!
}

type User {
  id: ID!
  name: String!
}

type Query {
  todos: [Todo!]!
}

input NewTodo {
  text: String!
  userId: String!
}

type Mutation {
  createTodo(input: NewTodo!): Todo!
}
```

**Comment by ExFly** [comment]
when i update go from 10 -> 11, then rm golang.org/x/tools, the error fix. It seems that the core lib x/tools is modied~~~

**Comment by vektah** [comment]
Weird, context should be present from go 1.7 onwards
