### ISSUE TITLE
Panic when model is a type definition of another package

### ISSUE THREAD

**Issue by marwan-at-work** [99designs/gqlgen#721]
### What happened?
if `gqlgen.yml` points to a custom type, and that custom type is defined as follows: 

```
type Custom somepkg.Custom
```

Then the `gqlgen` command panics with the following error: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x12f29f8]

goroutine 1 [running]:
github.com/99designs/gqlgen/codegen/config.(*Binder).ObjectPosition(0xc0011b1980, 0x16b5920, 0xc0053c57c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/me/gqlgen/codegen/config/binder.go:63 +0x1f8
github.com/99designs/gqlgen/codegen.(*builder).bindField(0xc00895f8c8, 0xc001b38a80, 0xc00cc493b0, 0x0, 0x0)
        /Users/me/gqlgen/codegen/field.go:116 +0x3b8
github.com/99designs/gqlgen/codegen.(*builder).buildField(0xc00895f8c8, 0xc001b38a80, 0xc0001efea0, 0x0, 0x1a86220, 0x0)
        /Users/me/gqlgen/codegen/field.go:64 +0x31d
github.com/99designs/gqlgen/codegen.(*builder).buildObject(0xc00895f8c8, 0xc0000cad80, 0x15c8f85, 0x6, 0x0)
        /Users/me/gqlgen/codegen/object.go:73 +0x4d4
github.com/99designs/gqlgen/codegen.BuildData(0xc0000ca240, 0x16a17a0, 0x1a854e0, 0x0)
        /Users/me/gqlgen/codegen/data.go:84 +0x461
github.com/99designs/gqlgen/api.Generate(0xc0000ca240, 0x0, 0x0, 0x0, 0x0, 0x16094e8)
        /Users/me/gqlgen/api/generate.go:37 +0x243
github.com/99designs/gqlgen/cmd.glob..func1(0xc0001e0000)
        /Users/me/gqlgen/cmd/gen.go:39 +0xa2
github.com/urfave/cli.HandleAction(0x150d860, 0x16086a0, 0xc0001e0000, 0xc000032300, 0x0)
        /Users/me/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:492 +0x7c
github.com/urfave/cli.(*App).Run(0xc0001d2000, 0xc0000c0000, 0x1, 0x1, 0x0, 0x0)
        /Users/me/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:264 +0x57c
github.com/99designs/gqlgen/cmd.Execute()
        /Users/me/gqlgen/cmd/root.go:40 +0x224
main.main()
        /Users/me/gqlgen/main.go:8 +0x20
```

### What did you expect?
To not panic, because if the `Custom` type was defined in the same package then `type Custom OtherCustom` would work fine. 

### Minimal graphql.schema and models to reproduce

```graphql
schema {
	query: Query
}

type Query {
	Create: TestMsg!
}

type TestMsg {
	field: String!
}
```

Then have gqlgen.yml be like this: 

```yaml
schema:
- schema.graphql
exec:
  filename: generated.go
model:
  filename: models_gen.go
resolver:
  filename: resolver.go
  type: Resolver
models:
  TestMsg:
    model:
    - path/to/my/module.TestMsg
```

And define TestMsg to point to another package as mentioned above. 

### versions
 - `gqlgen version`? v0.9.0
 - `go version`? v1.12.5
 - dep or go modules? Go Modules

**Comment by mathewbyrne** [comment]
Ok, so if the type you're mapping to is a type alias to a different base type generation fails?

**Comment by marwan-at-work** [comment]
@mathewbyrne not necessarily a type alas: `type Custom = somepkg.Custom` but any type decl of an external package `type Custom somepkg.Custom`
