### ISSUE TITLE
Subscriptions cause leaking goroutines

### ISSUE THREAD

**Issue by alexzimmer96** [99designs/gqlgen#763]
### What happened?
When i was checking metrics on my example project, i saw that after every subscription i close the number of active goroutines increased by 2. After some research, i figured out which goroutines keep alive even if the subscription is already closed:

```
goroutine 42 [select]:
github.com/99designs/gqlgen/handler.(*wsConnection).keepAlive(0xc0000e8ea0, 0xa32600, 0xc000053a40)
	D:/Go/pkg/mod/github.com/99designs/gqlgen@v0.9.0/handler/websocket.go:165 +0xdd
created by github.com/99designs/gqlgen/handler.(*wsConnection).run
	D:/Go/pkg/mod/github.com/99designs/gqlgen@v0.9.0/handler/websocket.go:128 +0x49f

goroutine 113 [IO wait, 8 minutes]:
internal/poll.runtime_pollWait(0x1414d68, 0x72, 0xa29f00)
	C:/Go/src/runtime/netpoll.go:182 +0x5d
internal/poll.(*pollDesc).wait(0xc0000d81c8, 0x72, 0xd83400, 0x0, 0x0)
	C:/Go/src/internal/poll/fd_poll_runtime.go:87 +0xa2
internal/poll.(*ioSrv).ExecIO(0xdbf740, 0xc0000d8018, 0x9a5aa0, 0x2, 0x3, 0x4)
	C:/Go/src/internal/poll/fd_windows.go:228 +0x124
internal/poll.(*FD).Read(0xc0000d8000, 0xc0002f0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	C:/Go/src/internal/poll/fd_windows.go:502 +0x26b
net.(*netFD).Read(0xc0000d8000, 0xc0002f0000, 0x1000, 0x1000, 0xc00051f3b8, 0x10, 0x0)
	C:/Go/src/net/fd_windows.go:152 +0x56
net.(*conn).Read(0xc00009c610, 0xc0002f0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	C:/Go/src/net/net.go:177 +0x70
bufio.(*Reader).fill(0xc0000e8e40)
	C:/Go/src/bufio/bufio.go:100 +0x116
bufio.(*Reader).Peek(0xc0000e8e40, 0x2, 0x50809b, 0x8c4fc0, 0x0, 0x0, 0x0)
	C:/Go/src/bufio/bufio.go:138 +0x56
github.com/gorilla/websocket.(*Conn).read(0xc00013d760, 0x2, 0xc00051f4e8, 0x414067, 0xc000152378, 0x10, 0x10)
	D:/Go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:357 +0x47
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc00013d760, 0x0, 0x0, 0x0)
	D:/Go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:787 +0x63
github.com/gorilla/websocket.(*Conn).NextReader(0xc00013d760, 0x0, 0x0, 0xc00051f668, 0x4e500e, 0xc00006c5c0)
	D:/Go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:947 +0xa7
github.com/99designs/gqlgen/handler.(*wsConnection).readOp(0xc0000e8ea0, 0xc00010eae0)
	D:/Go/pkg/mod/github.com/99designs/gqlgen@v0.9.0/handler/websocket.go:295 +0x3a
github.com/99designs/gqlgen/handler.(*wsConnection).run(0xc0000e8ea0)
	D:/Go/pkg/mod/github.com/99designs/gqlgen@v0.9.0/handler/websocket.go:132 +0xb1
github.com/99designs/gqlgen/handler.connectWs(0xa33880, 0xc00018c3f0, 0xa31700, 0xc0004e2700, 0xc0002e6f00, 0xc000182f00, 0xc0001034a0)
	D:/Go/pkg/mod/github.com/99designs/gqlgen@v0.9.0/handler/websocket.go:77 +0x3ee
github.com/99designs/gqlgen/handler.(*graphqlHandler).ServeHTTP(0xc000004f80, 0xa31700, 0xc0004e2700, 0xc0002e6f00)
	D:/Go/pkg/mod/github.com/99designs/gqlgen@v0.9.0/handler/graphql.go:355 +0x122f
net/http.HandlerFunc.ServeHTTP(0xc000050450, 0xa31700, 0xc0004e2700, 0xc0002e6f00)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0000264e0, 0xa31700, 0xc0004e2700, 0xc0002e6f00)
	D:/Go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/mux.go:425 +0x286
net/http.HandlerFunc.ServeHTTP(0xc000050460, 0xa31700, 0xc0004e2700, 0xc0002e6f00)
	C:/Go/src/net/http/server.go:1995 +0x4b
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0000264e0, 0xa31700, 0xc0004e2700, 0xc0002e6e00)
	D:/Go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/mux.go:82 +0x29b
net/http.serverHandler.ServeHTTP(0xc000162750, 0xa31700, 0xc0004e2700, 0xc0002e6e00)
	C:/Go/src/net/http/server.go:2774 +0xaf
net/http.(*conn).serve(0xc00006a000, 0xa32600, 0xc000053180)
	C:/Go/src/net/http/server.go:1878 +0x858
created by net/http.(*Server).Serve
	C:/Go/src/net/http/server.go:2884 +0x2fb
```
It seems like that the keepAlive function did never receive the ending context.

### What did you expect?
Goroutine should be closed when a subscription is closed

### How to Reproduce
My example project is available at https://github.com/alexzimmer96/gqlgen-example
You could reproduce by starting the project, visiting `localhost:1337/playground` and starting a subscription. Take a look at `localhost:1337/metrics` and `localhost:1337/_stack` and you will see the active number of goroutines increasing. The stack-endpoint containing more information about the living routines.

This error should also be comprehensibly by any other implemented subscription. I just tested it with the provided chat-example. Same result.

### versions
 - gqlgen-version: `v0.9.0`
 - go-version: `go1.12.5`
 - go modules

**EDIT**
Played around a little bit more and it seems the connection just does not close when the subscription is canceled, e.g. by clicking the play/stop button in playground again.

**Comment by vektah** [comment]
So this is a bug in playground?

I'm not seeing any obvious leaks in our production apps:
![image](https://user-images.githubusercontent.com/2247982/60218223-0bbc4800-98b2-11e9-96b3-18e5cfeb4c62.png)

**Comment by alexzimmer96** [comment]
Hi Vektah, thank you for the response.
But even if this is a bug in playground, how it is possible that a not properly terminated connection could leave the keepAlive-Checking goroutine open? Maybe i did something wrong in my implementation?

```
func (r *subscriptionResolver) ArticleCreated(ctx context.Context) (<-chan *model.Article, error) {
	// ...
	incoming := subscription.CreationStream
	returningChannel := make(chan *model.Article)
	go func() {
		for {
			select {
			case <-ctx.Done():
				r.articleService.UnsubscribeArticleCreation(subscription)
				close(incoming)
				close(returningChannel)
				return
			case article := <-incoming:
				returningChannel <- article
			}
		}
	}()
	return returningChannel, nil
}
```

**Comment by alexzimmer96** [comment]
@vektah Thanks for your support - I found the failure. You where right. The leaking go-routines disappeared when i closed the Playground-Tab. It seems, playground does not close the websocket until playground is closed.
