### ISSUE TITLE
get started doc failing.

### ISSUE THREAD

**Issue by NicTanghe** [99designs/gqlgen#867]
### What happened?
`go run github.com/99designs/gqlgen -v`

returns

```
C:\Users\nicta\Documents\dev\go\qglgen_test
λ  go run github.com/99designs/gqlgen -v
panic: unable to find type github.com/nictanghe/gqlgen-todos.Todo


goroutine 1 [running]:
github.com/99designs/gqlgen/codegen.(*builder).bindField.func1(0xc0006e7200, 0xc000395858)
        C:/Users/nicta/go/pkg/mod/github.com/99designs/gqlgen@v0.9.3/codegen/field.go:81 +0xb3
github.com/99designs/gqlgen/codegen.(*builder).bindField(0xc000395858, 0xc00424e600, 0xc0006e7200, 0x0, 0x0)
        C:/Users/nicta/go/pkg/mod/github.com/99designs/gqlgen@v0.9.3/codegen/field.go:100 +0xeb0
github.com/99designs/gqlgen/codegen.(*builder).buildField(0xc000395858, 0xc00424e600, 0xc004ff0d90, 0x0, 0xe6a700, 0xc004390e70)
        C:/Users/nicta/go/pkg/mod/github.com/99designs/gqlgen@v0.9.3/codegen/field.go:64 +0x324
github.com/99designs/gqlgen/codegen.(*builder).buildObject(0xc000395858, 0xc004ff4000, 0x9e7c2b, 0x6, 0x0)
        C:/Users/nicta/go/pkg/mod/github.com/99designs/gqlgen@v0.9.3/codegen/object.go:73 +0x4ee
github.com/99designs/gqlgen/codegen.BuildData(0xc0001aa000, 0xac10c0, 0xe698e0, 0x0)
        C:/Users/nicta/go/pkg/mod/github.com/99designs/gqlgen@v0.9.3/codegen/data.go:89 +0x490
github.com/99designs/gqlgen/api.Generate(0xc0001aa000, 0x0, 0x0, 0x0, 0x0, 0xc0000b1220)
        C:/Users/nicta/go/pkg/mod/github.com/99designs/gqlgen@v0.9.3/api/generate.go:39 +0x20b
github.com/99designs/gqlgen/cmd.glob..func1(0xc0001a4000)
        C:/Users/nicta/go/pkg/mod/github.com/99designs/gqlgen@v0.9.3/cmd/gen.go:39 +0xa8
github.com/urfave/cli.HandleAction(0x923b20, 0xa2b018, 0xc0001a4000, 0xc000064120, 0x0)
        C:/Users/nicta/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:492 +0x83
github.com/urfave/cli.(*App).Run(0xc000198000, 0xc000004480, 0x2, 0x2, 0x0, 0x0)
        C:/Users/nicta/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:264 +0x593
github.com/99designs/gqlgen/cmd.Execute()
        C:/Users/nicta/go/pkg/mod/github.com/99designs/gqlgen@v0.9.3/cmd/root.go:40 +0x22b
main.main()
        C:/Users/nicta/go/pkg/mod/github.com/99designs/gqlgen@v0.9.3/main.go:8 +0x27
exit status 2
```

### What did you expect?
shit working dub
### versions
 - `gqlgen version`? 
v0.9.3
 - `go version`?
1.13
 - dep or go modules?

**Comment by vektah** [comment]
Theres not really enough to go off here. Whats in the directory?
