### ISSUE TITLE
Panic if only interfaces shall be generated

### ISSUE THREAD

**Issue by fridolin-koch** [99designs/gqlgen#930]
### What happened?

A Panic occurs if only interfaces shall be generated by the model generator plugin:

```
panic: unable to find type github.com/fridolin-koch/gqlgen-bug.Node


goroutine 1 [running]:
github.com/99designs/gqlgen/codegen.(*builder).buildInterface(0xc000201858, 0xc0000d4cc0, 0xc000201880)
	/Users/frido/Go/pkg/mod/github.com/99designs/gqlgen@v0.10.1/codegen/interface.go:26 +0x39d
github.com/99designs/gqlgen/codegen.BuildData(0xc0001d4000, 0x16cfe20, 0x1a90948, 0x0)
	/Users/frido/Go/pkg/mod/github.com/99designs/gqlgen@v0.10.1/codegen/data.go:104 +0x3e3
github.com/99designs/gqlgen/api.Generate(0xc0001d4000, 0x0, 0x0, 0x0, 0x0, 0xc0000df220)
	/Users/frido/Go/pkg/mod/github.com/99designs/gqlgen@v0.10.1/api/generate.go:39 +0x204
github.com/99designs/gqlgen/cmd.glob..func1(0xc0001d2000)
	/Users/frido/Go/pkg/mod/github.com/99designs/gqlgen@v0.10.1/cmd/gen.go:39 +0xa1
github.com/urfave/cli.HandleAction(0x152b860, 0x1634e00, 0xc0001d2000, 0xc000082180, 0x0)
	/Users/frido/Go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:492 +0x7c
github.com/urfave/cli.(*App).Run(0xc0001c6000, 0xc0000bc010, 0x1, 0x1, 0x0, 0x0)
	/Users/frido/Go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:264 +0x58c
github.com/99designs/gqlgen/cmd.Execute()
	/Users/frido/Go/pkg/mod/github.com/99designs/gqlgen@v0.10.1/cmd/root.go:40 +0x224
main.main()
	/Users/frido/Go/pkg/mod/github.com/99designs/gqlgen@v0.10.1/main.go:8 +0x20
exit status 2
```

### What did you expect?

No Panic :)

### Minimal graphql.schema and models to reproduce

Based on "Getting Started"

https://github.com/fridolin-koch/gqlgen-bug

Just run `go run github.com/99designs/gqlgen`

### versions
 - `v0.10.1` 
 - `go version go1.13 darwin/amd64`
 - go modules?

I'm pretty sure the problem is the following line:

https://github.com/99designs/gqlgen/blob/15b30588a1451bbe280660a1d6cf629f50121d86/plugin/modelgen/models.go#L230

I guess it should be

```go
if len(b.Models) == 0 && len(b.Enums) == 0 && len(b.Interfaces) == 0 && len(b.Scalars) == 0 {
```

Best Regards!

**Comment by vektah** [comment]
fixed in https://github.com/99designs/gqlgen/pull/931
