### ISSUE TITLE
Panic if type name "Subscription"

### ISSUE THREAD

**Issue by Yamashou** [99designs/gqlgen#957]
### What happened?
A panic occurs if define type of Subscription
```
type Subscription implements Node {
    id: ID!
    userID: ID!
    deadline: Int!
    createdAt: Int!
    updatedAt: Int!
}
```
```
panic: Subscription was not found

goroutine 1 [running]:
github.com/99designs/gqlgen/codegen.(*builder).bindField.func1(0xc000c4ad80, 0xc002603658)
        /Users/foo/go/pkg/mod/github.com/99designs/gqlgen@v0.9.1/codegen/field.go:81 +0xac
github.com/99designs/gqlgen/codegen.(*builder).bindField(0xc002603658, 0xc00669cd00, 0xc000c4ad80, 0x16cb120, 0xc005d5b8b0)
        /Users/foo/go/pkg/mod/github.com/99designs/gqlgen@v0.9.1/codegen/field.go:169 +0xbf2
github.com/99designs/gqlgen/codegen.(*builder).buildField(0xc002603658, 0xc00669cd00, 0xc0046ed650, 0x0, 0x2, 0xc005d5b870)
        /Users/foo/go/pkg/mod/github.com/99designs/gqlgen@v0.9.1/codegen/field.go:64 +0x31d
github.com/99designs/gqlgen/codegen.(*builder).buildObject(0xc002603658, 0xc0046ee840, 0x15eef8c, 0x6, 0x0)
        /Users/foo/go/pkg/mod/github.com/99designs/gqlgen@v0.9.1/codegen/object.go:73 +0x4ec
github.com/99designs/gqlgen/codegen.BuildData(0xc0001b2000, 0x16cb180, 0x1ac64a0, 0x0)
        /Users/foo/go/pkg/mod/github.com/99designs/gqlgen@v0.9.1/codegen/data.go:89 +0x492
github.com/99designs/gqlgen/api.Generate(0xc0001b2000, 0x0, 0x0, 0x0, 0x0, 0x13228c7)
        /Users/foo/go/pkg/mod/github.com/99designs/gqlgen@v0.9.1/api/generate.go:39 +0x285
github.com/99designs/gqlgen/cmd.glob..func1(0xc0001ae160)
        /Users/foo/go/pkg/mod/github.com/99designs/gqlgen@v0.9.1/cmd/gen.go:39 +0xa5
github.com/urfave/cli.HandleAction(0x152ee60, 0x162f080, 0xc0001ae160, 0xc000194100, 0x0)
        /Users/foo/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:492 +0x7c
github.com/urfave/cli.Command.Run(0x15f3c32, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x161ff69, 0x29, 0x0, ...)
        /Users/foo/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x996
github.com/urfave/cli.(*App).Run(0xc0000a81a0, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
        /Users/foo/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x6af
github.com/99designs/gqlgen/cmd.Execute()
        /Users/foo/go/pkg/mod/github.com/99designs/gqlgen@v0.9.1/cmd/root.go:40 +0x224
main.main()
        /Users/foo/go/pkg/mod/github.com/99designs/gqlgen@v0.9.1/main.go:8 +0x20
```
### What did you expect?
No Panic and generate code 

### Minimal graphql.schema and models to reproduce
```
type Subscription {
    id: ID!
    userID: ID!
    createdAt: Int!
    updatedAt: Int!
}
```
### versions
 - `gqlgen version`? 
v0.9.1
 - `go version`?
go version go1.12.9 darwin/amd64
 - dep or go modules?
go modules

**Comment by keithmattix** [comment]
`Subscription` is a reserved GraphQL type, and thus, the error you're facing is likely due to the code generator failing to process the duplication. I believe an error is desired, but errors like this could stand to have a more specific message.

**Comment by parkr** [comment]
A more specific message would be very helpful here. I had no trouble defining a Subscription object type in my GraphQL schema which works just fine between Apollo and our GraphQL Ruby server. When generating client code with this library, however, I receive a somewhat confusing panic, `Subscription was not found` (when, in fact, it's a misuse of a reserved type):

```text
2021/06/25 13:18:14 Subscription was not found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x12e461f]

goroutine 1 [running]:
github.com/99designs/gqlgen/codegen/config.(*TypeReference).IsPtr(...)
        /Users/parkr/go/pkg/mod/github.com/99designs/gqlgen@v0.10.2/codegen/config/binder.go:255
github.com/99designs/gqlgen/codegen.(*builder).buildField(0xc002bdbbc8, 0xc001187c80, 0xc0051f8380, 0x0, 0x1, 0xc000d8e958)
        /Users/parkr/go/pkg/mod/github.com/99designs/gqlgen@v0.10.2/codegen/field.go:70 +0x37f
github.com/99designs/gqlgen/codegen.(*builder).buildObject(0xc002bdbbc8, 0xc0051f6540, 0xc001187c00, 0x0, 0x0)
        /Users/parkr/go/pkg/mod/github.com/99designs/gqlgen@v0.10.2/codegen/object.go:73 +0x47f
github.com/99designs/gqlgen/codegen.BuildData(0xc0001f4000, 0xc0001f4000, 0x0, 0x0)
        /Users/parkr/go/pkg/mod/github.com/99designs/gqlgen@v0.10.2/codegen/data.go:89 +0x4ac
```

It is interesting – given that Apollo and GraphQL Ruby seem to accept this Subscription type, perhaps it is not unreasonable to support `Subscription implements Node` as an object type?

**Comment by parkr** [comment]
@vektah It looks like `Subscription` is just a _default_ root type name, which means it could easily be renamed and it's perfectly valid for us to use `Subscription` as a non-subscription object type. https://spec.graphql.org/draft/#sec-Root-Operation-Types.Default-Root-Operation-Type-Names

<img width="831" alt="Screen Shot 2021-06-28 at 11 07 27 AM" src="https://user-images.githubusercontent.com/237985/123659796-0e373c80-d801-11eb-81c2-59dc9984366d.png">

From my reading, if the Schema's `subscriptionType` is `null`, then subscriptions are not supported.

<img width="874" alt="Screen Shot 2021-06-28 at 11 09 07 AM" src="https://user-images.githubusercontent.com/237985/123660120-5fdfc700-d801-11eb-9f3a-dcf4667b2863.png">

<img width="358" alt="Screen Shot 2021-06-28 at 11 08 57 AM" src="https://user-images.githubusercontent.com/237985/123660171-6bcb8900-d801-11eb-84e9-bab7e89a1121.png">

<img width="782" alt="Screen Shot 2021-06-28 at 11 08 07 AM" src="https://user-images.githubusercontent.com/237985/123660210-74bc5a80-d801-11eb-8490-8a7a12ad628a.png">

**Comment by sneko** [comment]
Hi,

In my case that's different, I'm from the `v0.11.3` upgrading to latest... but now I no longer have a `SubscriptionResolver`, it's generated as a basic struct type.

I didn't see any mention of this, do you know how can I fix this? @lwc @vektah 

Thanks
